### ISSUE TITLE
Support for openai chat completions / non zero-shot prompts

### ISSUE THREAD

**Issue by muratsu** [typpo/promptfoo#38]
Support for prompts that are beyond zero-shot would be great. To give an example, see the snippet below:

```
openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Who won the world series in 2020?"}
  ]
)
```

The current examples eg. e-commerce assistant are all zero-shot.

**Comment by typpo** [comment]
Hi Murat!  This is actually supported right now.

Your `prompt.txt` (or `prompt.json`) would be:

```json
[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Who won the world series in {{ year }}?"}
]
```

Note that `{{ year }}` will be substituted with the appropriate test variable.

I'll keep this issue open as a reminder to update the docs/example.

**Comment by no-hype-ai** [comment]
**Phase 1 Complete ✅**

Successfully fixed the Vite/Terser build error.

**Changes Made**:
1. Switched from `minify: 'terser'` to `minify: 'esbuild'` (Vite 7 default minifier)
2. Added external configuration to exclude `vite-plugin-node-polyfills/shims` from bundling
3. Simplified terserOptions (no longer needed with esbuild)

**File Modified**:
- `src/app/vite.config.ts` (lines 49-55)

**Build Result**: ✅ Success
- Build completes without errors
- dist/src/app/ folder created with all assets
- Build time: 26.42s

**Validation**:
- [x] Vite configuration error resolved
- [x] `npm run build` completes without Vite errors  
- [x] `dist/` folder created with frontend assets

**Progress**: 100% | **Status**: COMPLETE
